config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :admins
  devise_for :customers
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "pages#home"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders 
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :order_items

  default_scope { where(active: true) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
  	@order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
  	@order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
  	@order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
      <h6><%= product.description %></h6>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html>
<html>
<head>
  <title>GKNew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
 -->


<!DOCTYPE html>
<html>
<head>
  <title>Grechelle's Kitchen</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>

<body>

<section id="products">
<div class="row">
  <p id="notice"><%= notice %></p>

  <p class="navbar-text pull-left">
  <% if customer_signed_in? %>
    Logged in as <strong><%= current_customer.email %></strong>.
    <%= link_to 'Edit profile', edit_customer_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_customer_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_customer_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_customer_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
<!--   <div class="col-xs-offset-1 pull-right">
    <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
  </div> -->


  <div class="headerimg">
<!--   <div class="ui secondary menu">
  <a class="item">
    <p id="notice"><%= notice %></p>

  <p class="navbar-text pull-left">
  <% if customer_signed_in? %>
    Logged in as <strong><%= current_customer.email %></strong>.
    <%= link_to 'Edit profile', edit_customer_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_customer_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_customer_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_customer_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  </a>
  <a class="item">
    Products
  </a>
</div> -->
<!--     <div class="nav-row row">
        <div class="col-xs-2 col-xs-offset-1 headerlinks"><%= link_to "Home", root_path %></div>
        <div class="col-xs-2 headerlinks"><%= link_to "Products", products_path %></div>
        <div class="col-xs-2 col-xs-offset-2 headerlinks"><%= link_to "My Cart", cart_path %></div>
        <div class="col-xs-2 headerlinks"><%= link_to "Verify", root_path %></div>
    </div> -->
<br><br><br>
    <div class="ui centered grid">
        <div class="two wide column"></div>
        <div class="two wide column headerlinks"><%= link_to "Home", root_path %></div>
        <div class="two wide column headerlinks"><%= link_to "Products", products_path %></div>
        <div class="four wide column headerlinks"><%= link_to " ",root_path %></div>
        <div class="one wide column"></div>
        <div class="two wide column headerlinks"><%= link_to "My Cart", cart_path %></div>
        <div class="two wide column headerlinks"><%= link_to "Verify", root_path %></div>
        <div class="one wide column"></div>
  </div>
  <br>

</div>
<br>
</section>
  <!-- <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "My Store", root_path %></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <hr> -->
    <%= yield %>
  <!-- </div> -->
  <br><br>
  <div class="footerimg">
  </div>
</body>
</html>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/pages/home.html.erb
<section id="products">
<div class="ui action input">
  <input type="text" placeholder="Search for products...">
  <button class="ui button">Search</button>
</div>

<br><br>

<div>
<img src="/assets/forHome.jpg" class="img-responsive" alt="Responsive image">
</div>

<br><br>

<div class="ui grid container">
	<div class="eight wide column">
		<div class="ui card">
		  <a class="image" href="#">
		    <img src="assets/placeholder.jpg">
		  </a>
		  <div class="content">
		    <a class="header" href="#">We customize!</a>
		    <div class="meta">
		      <a>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</a>
		    </div>
		  </div>
		</div>
	</div>
	<div class="eight wide column">
		<div class="ui card">
		  <a class="image" href="#">
		    <img src="assets/placeholder.jpg">
		  </a>
		  <div class="content">
		    <a class="header" href="#">We customize!</a>
		    <div class="meta">
		      <a>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</a>
		    </div>
		  </div>
		</div>
	</div>
</div>
</section>

app/views/pages/index.html.erb
<!-- <div class ="col-xs-offset-3 col-xs-6 col-md-offset-3 col-md-6">
 -->

<section id="products">

<!-- <p class="navbar-text pull-left"
 -->
 


 <!-- <div class="slider">
    <ul class="slides">
      <li>
        <img src='/assets/forHome.jpg'>
        <div class="caption center-align">
          <h3>This is our big Tagline!</h3>
          <h5 class="light grey-text text-lighten-3">blah</h5>
        </div>
      </li>
    </ul>
 </div> -->

<div>
<img src="/assets/forHome.jpg" class="img-responsive" alt="Responsive image">
</div>

<br>

<div class="row">

  <div class="col s6">
    <!-- Promo Content 1 goes here -->
    <div class="card">
      <div class="card-image">
        <img src="/assets/placeholder.jpg">
        <span class="card-title"><a href="#">We accept bulk orders!</a></span>
      </div>
      <div class="card-content">
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <!-- <div class="card-action">
        <a href="#">This is a link</a>
      </div> -->
    </div>
  </div>
  <div class="col s12 m6">
    <div class="card cyan lighten-3">
      <div class="card-content black-text">
        <span class="card-title"><a href="#">Have you ordered?</a></span>
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>
  <div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Already paid?</span>
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <div class="card-action">
        <a href="#">This is a link</a>
        <a href="#">This is a link</a>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s6">
    <!-- Promo Content 3 goes here -->
    <div class="card">
      <div class="card-image">
        <img src="/assets/placeholder.jpg">
        <span class="card-title">We customize!</span>
      </div>
      <div class="card-content">
        <p>I am a very simple card. I am good at containing small bits of information.
        I am convenient because I require little markup to use effectively.</p>
      </div>
      <!-- <div class="card-action">
        <a href="#">This is a link</a>
      </div> -->
    </div>
  </div>
<!--   <div class="col s6">
 -->    <!-- Promo Content 2 goes here -->
 <center>
    <div class="col s12 m6">
      <div class="white">
        <div class="card-content black-text">
          <span class="card-title">Contact details</span>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.
          <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></p>
        </div>
        <!-- <div class="card-action">
          <a href="#">This is a link</a>
          <a href="#">This is a link</a>
        </div> -->
      </div>
    </div>
    </center>
<!--   </div>
 -->
</div>

</section>

<!-- </div>
 -->
<br>


<%# link_to 'New Product', new_product_path %>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
      <h6><%= product.description %></h6>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>